[package]
name = "cozyreq_tui"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
color-eyre.workspace = true
crossterm.workspace = true
ratatui.workspace = true

[dev-dependencies]
insta.workspace = true
